apiVersion: v2
name: grafana
description: The leading tool for querying and visualizing time series and metrics.
type: application
version: 9.2.1
appVersion: "12.0.0"
kubeVersion: "^1.8.0-0"
home: https://grafana.com
sources:
  - https://github.com/grafana/grafana
  - https://github.com/grafana/helm-charts
keywords:
  - monitoring
  - metric
maintainers:
  - name: grafana
    url: https://grafana.com